In [2]:
import pandas as pd 


data = pd.read_csv("./month_fill.csv", encoding='utf-8')

In [3]:
data

,TA_YM,MCT_RY_NM,MCTNM,BRD_NM,ARED,BZNCD,LALXCVL,LALYCVL,EST_AMT_TOT,EST_CNT_TOT,...,소득5천만이하,소득7천만이하,소득1억이하,소득1억초과,생애단계_싱글,생애단계_영유아,생애단계_청소년,MCT_BSE_AR,MCT_RY_NM2,OUB_RY_MI_CZ_NM
0,202301,한식,"""미 ""갈매기살전문",NaN,20031105,익선동,126.991069,37.573007,32082497.0,442,...,41.902,20.308,13.501,4.576,68.725,2.912,17.340,서울 종로구 돈화문로11가길 7,한식,한식
1,202302,한식,"""미 ""갈매기살전문",NaN,20031105,익선동,126.991069,37.573007,51156355.0,704,...,34.331,28.429,9.758,7.113,60.367,6.643,20.998,서울 종로구 돈화문로11가길 7,한식,한식
2,202303,한식,"""미 ""갈매기살전문",NaN,20031105,익선동,126.991069,37.573007,54534440.0,733,...,37.938,19.830,11.116,12.763,45.212,7.570,28.394,서울 종로구 돈화문로11가길 7,한식,한식
3,202304,한식,"""미 ""갈매기살전문",NaN,20031105,익선동,126.991069,37.573007,84513865.0,1015,...,43.340,13.873,10.164,12.144,57.957,9.534,15.989,서울 종로구 돈화문로11가길 7,한식,한식
4,202305,한식,"""미 ""갈매기살전문",NaN,20031105,익선동,126.991069,37.573007,70911682.0,850,...,38.152,21.813,12.378,7.416,58.094,5.134,16.537,서울 종로구 돈화문로11가길 7,한식,한식
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1410719,202308,양식,（주）에스알인베,NaN,20100121,수서역,127.103227,37.488510,49810547.0,1128,...,22.435,19.344,18.120,28.904,24.578,11.407,39.024,"서울 강남구 광평로51길 6-11,",양식,NaN
1410720,202309,양식,（주）에스알인베,NaN,20100121,수서역,127.103227,37.488510,40096531.0,1015,...,27.881,19.919,12.677,29.676,28.544,13.324,36.674,"서울 강남구 광평로51길 6-11,",양식,NaN
1410721,202310,양식,（주）에스알인베,NaN,20100121,수서역,127.103227,37.488510,33497913.0,874,...,28.690,22.706,17.848,23.248,32.342,16.282,26.179,"서울 강남구 광평로51길 6-11,",양식,NaN
1410722,202311,양식,（주）에스알인베,NaN,20100121,수서역,127.103227,37.488510,29845619.0,853,...,29.292,14.482,12.809,27.874,34.191,20.221,24.117,"서울 강남구 광평로51길 6-11,",양식,NaN
1410723,202312,양식,（주）에스알인베,NaN,20100121,수서역,127.103227,37.488510,39197200.0,1059,...,27.469,22.908,15.956,24.171,35.973,13.198,34.431,"서울 강남구 광평로51길 6-11,",양식,NaN

In [4]:
# 매출데이터가 빈값이 있는지 확인하자.

data.columns

Index(['TA_YM', 'MCT_RY_NM', 'MCTNM', 'BRD_NM', 'ARED', 'BZNCD', 'LALXCVL',
       'LALYCVL', 'EST_AMT_TOT', 'EST_CNT_TOT', 'WKND_RT', '시간_0813',
       '시간_1417', '시간_1821', '시간_2207', '남성_20대', '남성_30대', '남성_40대', '남성_50대',
       '남성_60대', '여성_20대', '여성_30대', '여성_40대', '여성_50대', '여성_60대', '소득정보없음',
       '소득3천만이하', '소득5천만이하', '소득7천만이하', '소득1억이하', '소득1억초과', '생애단계_싱글',
       '생애단계_영유아', '생애단계_청소년', 'MCT_BSE_AR', 'MCT_RY_NM2', 'OUB_RY_MI_CZ_NM'],
      dtype='object')

In [7]:
data['EST_AMT_TOT'].isnull().value_counts() # 빈값은 없음.

EST_AMT_TOT
False    1410724
Name: count, dtype: int64

In [55]:
# 30개 무작위 추출하여 확인하자! 

data[data['MCTNM'] == '(주)경성키친']

,TA_YM,MCT_RY_NM,MCTNM,BRD_NM,ARED,BZNCD,LALXCVL,LALYCVL,EST_AMT_TOT,EST_CNT_TOT,...,소득5천만이하,소득7천만이하,소득1억이하,소득1억초과,생애단계_싱글,생애단계_영유아,생애단계_청소년,MCT_BSE_AR,MCT_RY_NM2,OUB_RY_MI_CZ_NM
5335,202303,식품잡화,(주)경성키친,NaN,20200728,NaN,127.027739,37.568476,700264.0,33,...,38.945,13.693,0.000,0.000,47.362,0.000,13.693,서울특별시 성동구 무학로 33,식품,별식/퓨전요리
5336,202304,식품잡화,(주)경성키친,NaN,20200728,NaN,127.027739,37.568476,473517.0,24,...,100.000,0.000,0.000,0.000,39.873,60.127,0.000,서울특별시 성동구 무학로 33,식품,별식/퓨전요리
5337,202305,식품잡화,(주)경성키친,NaN,20200728,NaN,127.027739,37.568476,1078983.0,51,...,27.695,7.434,43.996,6.004,23.254,11.875,55.194,서울특별시 성동구 무학로 33,식품,별식/퓨전요리
5338,202306,식품잡화,(주)경성키친,NaN,20200728,NaN,127.027739,37.568476,893825.5,0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,서울특별시 성동구 무학로 33,식품,별식/퓨전요리
5339,202307,식품잡화,(주)경성키친,NaN,20200728,NaN,127.027739,37.568476,708668.0,33,...,11.990,41.053,33.601,13.356,22.917,18.440,45.288,서울특별시 성동구 무학로 33,식품,별식/퓨전요리
5340,202308,식품잡화,(주)경성키친,NaN,20200728,NaN,127.027739,37.568476,2221982.0,98,...,27.799,4.590,26.546,25.595,30.370,5.623,36.507,서울특별시 성동구 무학로 33,식품,별식/퓨전요리
5341,202309,식품잡화,(주)경성키친,NaN,20200728,NaN,127.027739,37.568476,1044332.0,52,...,0.000,23.431,22.149,0.000,45.685,12.027,33.554,서울특별시 성동구 무학로 33,식품,별식/퓨전요리
5342,202310,식품잡화,(주)경성키친,NaN,20200728,NaN,127.027739,37.568476,3224695.0,125,...,9.900,18.354,45.400,10.614,40.731,8.482,40.377,서울특별시 성동구 무학로 33,식품,별식/퓨전요리
5343,202311,식품잡화,(주)경성키친,NaN,20200728,NaN,127.027739,37.568476,1320022.0,64,...,59.660,14.814,19.178,0.000,76.898,0.000,14.814,서울특별시 성동구 무학로 33,식품,별식/퓨전요리
5344,202312,식품잡화,(주)경성키친,NaN,20200728,NaN,127.027739,37.568476,985862.0,48,...,77.150,0.000,22.850,0.000,100.000,0.000,0.000,서울특별시 성동구 무학로 33,식품,별식/퓨전요리