In [1]:
import pandas as pd

### 서울 지하철역 데이터 불러오기

In [2]:
subway = pd.read_csv('data/상권 관련/서울시 지하철역 정보 검색 (역명).csv', encoding='cp949', index_col=None)

In [3]:
subway

    전철역코드   전철역명      호선  외부코드
0    0008     수서   GTX-A  X108
1    0009     성남   GTX-A  X109
2    0011     동탄   GTX-A  X111
3    0228  서울대입구    02호선   228
4    0318     안국    03호선   328
..    ...    ...     ...   ...
779  4925   걸포북변  김포도시철도   695
780  4926     사우  김포도시철도   696
781  1271     능곡     경의선  K321
782  1326     강촌     경춘선  P137
783  0300     대곡     경의선  K322

[784 rows x 4 columns]

### 전철역명 데이터 끝자리에 '역' 추가

In [4]:
subway['전철역명'] = subway['전철역명'].apply(lambda x: x + '역' if not x.endswith('역') else x)

In [5]:
subway

    전철역코드    전철역명      호선  외부코드
0    0008     수서역   GTX-A  X108
1    0009     성남역   GTX-A  X109
2    0011     동탄역   GTX-A  X111
3    0228  서울대입구역    02호선   228
4    0318     안국역    03호선   328
..    ...     ...     ...   ...
779  4925   걸포북변역  김포도시철도   695
780  4926     사우역  김포도시철도   696
781  1271     능곡역     경의선  K321
782  1326     강촌역     경춘선  P137
783  0300     대곡역     경의선  K322

[784 rows x 4 columns]

In [7]:
# subway.to_csv('서울 지하철역.csv', index=False, encoding='utf-8-sig')

### 서울 생활인구 데이터 불러오기

In [6]:
population = pd.read_csv('data/상권 관련/서울시 상권분석서비스(길단위인구-상권).csv', encoding='cp949', index_col=None)

In [7]:
population

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
0,20234,U,관광특구,3001496,강남 마이스 관광특구,113583,55514,58069,8833,22861,...,28141,24240,6152,15176,16745,18117,18747,18309,14392,12097
1,20234,U,관광특구,3001495,잠실 관광특구,4188496,2017386,2171109,454687,919145,...,670747,912724,486944,580239,581684,587837,595722,613310,641593,588110
2,20234,U,관광특구,3001494,종로?청계 관광특구,8613395,4590188,4023206,343998,1502424,...,1833304,1745935,691083,1258499,1354499,1400887,1401012,1393491,1015269,789736
3,20234,U,관광특구,3001493,동대문패션타운 관광특구,3567105,1682368,1884737,194293,681871,...,544798,652209,431849,535869,560640,576781,577323,540454,392367,383671
4,20234,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,7260770,3509141,3751628,375263,1263972,...,1785787,1492848,378934,1070516,1172856,1209127,1207932,1182093,770067,648178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32989,20191,A,골목상권,3110005,세검정,129171,55368,73803,19624,15305,...,13667,21367,20706,18686,18746,18727,18736,18576,17782,17918
32990,20191,A,골목상권,3110004,대신고등학교,495628,226246,269381,94335,57494,...,70258,94736,65414,69892,70158,71562,71577,70647,70556,71236
32991,20191,A,골목상권,3110003,세검정초등학교,706686,310470,396215,128431,82037,...,74478,96768,85012,100783,100429,100067,99815,98912,102760,103921
32992,20191,A,골목상권,3110002,독립문역 1번,540585,246868,293717,96885,65609,...,75590,96631,70361,76301,77283,79044,78826,78583,75041,75508
32993,20191,A,골목상권,3110001,이북5도청사,155680,68432,87248,27743,15216,...,17671,22780,19199,21722,21682,21627,21636,21604,23276,24132

### 생활인구 데이터에서 지하철역에 해당하는 데이터만 필터링

In [8]:
# subway 데이터프레임의 '전철역명'을 리스트로 변환
subway_station_list = subway['전철역명'].tolist()

# '상권_코드_명' 컬럼에서 subway 데이터프레임의 '전철역명'을 포함하는 행을 필터링
seoul = population[population['상권_코드_명'].apply(lambda x: any(station in x for station in subway_station_list))]

In [9]:
seoul

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
58,20234,R,전통시장,3130271,남성역골목시장,546301,239914,306387,62467,91868,...,64320,104968,80403,76916,76638,77187,76430,77042,81145,80944
79,20234,R,전통시장,3130248,영등포역지하도상점가,122008,59672,62337,8163,28538,...,18500,23909,14288,16743,16820,16878,17026,18049,19027,17463
86,20234,R,전통시장,3130241,선유도역 골목형상점가,306933,157860,149073,28904,55533,...,42164,50262,35391,44237,46341,47054,46892,46406,38848,37155
169,20234,R,전통시장,3130158,상계역전종합상가,183645,83994,99652,25071,23420,...,21294,33460,24976,26157,25527,25666,25483,25794,27556,27462
174,20234,R,전통시장,3130153,창동역상점가,192382,95763,96618,18890,28499,...,41639,44826,17042,24957,25317,26266,25999,28313,32109,29424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32964,20191,A,골목상권,3110030,동대문역 3번,196492,93587,102904,15547,23099,...,26552,35008,24908,27322,28025,28200,28408,29366,28116,27056
32965,20191,A,골목상권,3110029,동대문역 1번,2786089,1314319,1471768,298605,345135,...,302411,430575,361462,398388,395429,392201,392172,389193,404272,414434
32967,20191,A,골목상권,3110027,혜화역 1번,593312,256130,337183,65726,161168,...,90462,125862,70637,77261,79668,82473,83539,84988,94663,90721
32968,20191,A,골목상권,3110026,종로5가역 4번,442341,242939,199402,24198,59408,...,85880,78805,38193,66306,65980,66737,70441,69582,58826,44468
32992,20191,A,골목상권,3110002,독립문역 1번,540585,246868,293717,96885,65609,...,75590,96631,70361,76301,77283,79044,78826,78583,75041,75508

### 지하철역 및 출구에 해당하지 않는 데이터 확인 (전통시장)

In [10]:
seoul[seoul['상권_구분_코드_명'] == '전통시장']

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
58,20234,R,전통시장,3130271,남성역골목시장,546301,239914,306387,62467,91868,...,64320,104968,80403,76916,76638,77187,76430,77042,81145,80944
79,20234,R,전통시장,3130248,영등포역지하도상점가,122008,59672,62337,8163,28538,...,18500,23909,14288,16743,16820,16878,17026,18049,19027,17463
86,20234,R,전통시장,3130241,선유도역 골목형상점가,306933,157860,149073,28904,55533,...,42164,50262,35391,44237,46341,47054,46892,46406,38848,37155
169,20234,R,전통시장,3130158,상계역전종합상가,183645,83994,99652,25071,23420,...,21294,33460,24976,26157,25527,25666,25483,25794,27556,27462
174,20234,R,전통시장,3130153,창동역상점가,192382,95763,96618,18890,28499,...,41639,44826,17042,24957,25317,26266,25999,28313,32109,29424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31525,20191,R,전통시장,3130146,쌍문시장(쌍문역골목시장),1708686,772545,936141,192267,284669,...,211537,323862,230942,240782,241631,239985,239248,241880,251576,253586
31526,20191,R,전통시장,3130145,쌍문역둘리상점가,349088,159511,189576,35775,51488,...,42186,66948,56400,49828,49789,49673,49669,48663,51401,50064
31600,20191,R,전통시장,3130071,성수역 골목형상점가,32084,16947,15137,2265,6668,...,6607,7483,2713,4911,4908,5108,5344,5169,3648,2996
31601,20191,R,전통시장,3130070,뚝섬역상점가,504368,247643,256725,57042,80570,...,66339,81255,58734,73698,72529,74962,75276,74664,66644,66597
31608,20191,R,전통시장,3130063,신금호역 골목형상점가,297989,136869,161120,57018,31727,...,36125,51266,36556,41459,41366,41364,41174,41562,45015,46049

### 전통시장 제외

In [11]:
seoul = seoul[seoul['상권_구분_코드_명'] != '전통시장']

In [12]:
seoul

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
311,20234,D,발달상권,3120249,고덕역,513153,254560,258592,156515,51352,...,89901,122525,54027,72754,73916,74764,73955,76166,76732,64865
312,20234,D,발달상권,3120248,명일역,1504781,667229,837552,311931,146774,...,194238,282561,191601,212525,212787,213654,211853,216180,217870,219915
313,20234,D,발달상권,3120247,굽은다리역,710160,322544,387616,94210,89014,...,96070,140286,92064,101038,99489,99839,99347,100471,105806,104170
314,20234,D,발달상권,3120246,길동역,4412632,2074555,2338077,385856,702266,...,573116,761822,555975,625641,633994,635017,638214,645248,629965,604552
316,20234,D,발달상권,3120244,암사역,737658,347745,389912,100452,93811,...,96775,142827,93079,103647,103009,102682,102958,104834,112323,108205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32964,20191,A,골목상권,3110030,동대문역 3번,196492,93587,102904,15547,23099,...,26552,35008,24908,27322,28025,28200,28408,29366,28116,27056
32965,20191,A,골목상권,3110029,동대문역 1번,2786089,1314319,1471768,298605,345135,...,302411,430575,361462,398388,395429,392201,392172,389193,404272,414434
32967,20191,A,골목상권,3110027,혜화역 1번,593312,256130,337183,65726,161168,...,90462,125862,70637,77261,79668,82473,83539,84988,94663,90721
32968,20191,A,골목상권,3110026,종로5가역 4번,442341,242939,199402,24198,59408,...,85880,78805,38193,66306,65980,66737,70441,69582,58826,44468
32992,20191,A,골목상권,3110002,독립문역 1번,540585,246868,293717,96885,65609,...,75590,96631,70361,76301,77283,79044,78826,78583,75041,75508

In [26]:
# seoul.to_csv('서울 지하철역 생활인구.csv', index=False, encoding='utf-8-sig')