In [1]:
pip install pandas folium requests

Requirement already satisfied: pandas in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (2.1.2)
Collecting folium
  Downloading folium-0.16.0-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: requests in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: numpy<2,>=1.23.2 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from pandas) (1.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from pandas) (2023.3)
Collecting branca>=0.6.0 (from folium)
  Downloading branca-0.7.2-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: jinja2>=2.9 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from folium) (3.1.2)
Collecting xyzservices (from folium)
  Downloading xyzservices-2024.4.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from requests) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from requests) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from jinja2>=2.9->folium) (2.1.3)
Requirement already satisfied: six>=1.5 in /Users/leereh/anaconda3/envs/ssp_ws/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading folium-0.16.0-py2.py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0/100.0 kB 1.1 MB/s eta 0:00:00 0:00:01
Downloading branca-0.7.2-py3-none-any.whl (25 kB)
Downloading xyzservices-2024.4.0-py3-none-any.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.0/82.0 kB 2.3 MB/s eta 0:00:00
Installing collected packages: xyzservices, branca, folium
Successfully installed branca-0.7.2 folium-0.16.0 xyzservices-2024.4.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import requests 
import folium 
from folium import plugins

API_KEY = "AIzaSyDK0Ooj0UVwc449ETw-XaJuXFSwTIi_XtY"


data = pd.read_csv("./약수인근2019-2024유동인구.csv", index_col=False, encoding = "utf-8")

data2 = pd.read_csv("./약수인근2019-2024유동인구(2).csv" , index_col = False, encoding = 'utf-8')

In [2]:
data

        행정동  MZ세대_유동인구
0       약수동   13849466
1     금호1가동   20968457
2   금호2.3가동   35247485
3     금호4가동   17455188
4       다산동   27619424
5       장충동   19778916
6       청구동   20113711
7       동화동   16549135
8       신당동   44342124
9      신당5동   28850383
10      한남동   50289454
11      광희동   47989413
12    왕십리2동   30927428
13     행당1동   35129865
14     행당2동   24013350
15    이태원1동   24490174
16    이태원2동   25047865

In [3]:
data2

       행정동  MZ세대_유동인구
0      약수동   13849466
1    금호1가동   20968457
2  금호2.3가동   35247485
3    금호4가동   17455188
4      청구동   20113711
5      신당동   44342124
6     신당5동   28850383

In [4]:
df = pd.DataFrame(data)
df2 = pd.DataFrame(data2)

In [6]:
print(df)
print(df2)

        행정동  MZ세대_유동인구
0       약수동   13849466
1     금호1가동   20968457
2   금호2.3가동   35247485
3     금호4가동   17455188
4       다산동   27619424
5       장충동   19778916
6       청구동   20113711
7       동화동   16549135
8       신당동   44342124
9      신당5동   28850383
10      한남동   50289454
11      광희동   47989413
12    왕십리2동   30927428
13     행당1동   35129865
14     행당2동   24013350
15    이태원1동   24490174
16    이태원2동   25047865
       행정동  MZ세대_유동인구
0      약수동   13849466
1    금호1가동   20968457
2  금호2.3가동   35247485
3    금호4가동   17455188
4      청구동   20113711
5      신당동   44342124
6     신당5동   28850383

In [29]:
def geocode(address):
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
            'address' : address + ', Seoul, South Korea',
            'key' : API_KEY
    }

    response = requests.get(base_url, params=params)
    print(response)
    if response.status_code == 200:
        json_response = response.json()
        if json_response['results']:
            location = json_response['results'][0]['geometry']['location']
            return (location['lat'], location['lng'])
        
    return (None, None)


#Dataframe 위도 경도 추가
df['위도'], df['경도'] = zip(*df['행정동'].map(geocode))
df = df.dropna(subset = ['위도','경도']) # 유효하지 않은 위치 데이터는 제거 

#center lat, lng설정 
center_lat = df['위도'].mean()
center_lng = df['경도'].mean()

#Folium생성
map = folium.Map(location=[center_lat,center_lng], zoom_start = 12)


# heatmap으로 표현하여 시각적으로 보기 위해 표현. 
heat_data = [[row['위도'], row['경도'], row['MZ세대_유동인구']] for idx , row in df.iterrows()]
heat_map = plugins.HeatMap(heat_data, radius=40, max_zoom=13, blur=15,max_val = 1.0)
map.add_child(heat_map)


# 잘 보이지 않으니 마커를 추가하자
for idx , row in df.iterrows():
    if row['위도'] is not None and row['경도'] is not None:
        folium.Marker(
            location = (row['위도'], row['경도']),
            popup = f'{row["행정동"]} : 유동인구 {row["MZ세대_유동인구"]}',
            icon = folium.Icon(color = 'blue', icon = 'info-sign')
                    
        ).add_to(map)
    else :
        print(row['행정동'])


#지도저장 


map.save('heatmap.html')

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

/var/folders/06/tbmdvc413xncjxzs56w_xd100000gn/T/ipykernel_11828/267018737.py:33: UserWarning: The `max_val` parameter is no longer necessary. The largest intensity is calculated automatically.
  heat_map = plugins.HeatMap(heat_data, radius=40, max_zoom=13, blur=15,max_val = 1.0)

In [10]:
def geocode(address):
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
            'address' : address + ', Seoul, South Korea',
            'key' : API_KEY
    }

    response = requests.get(base_url, params=params)
    print(response)
    if response.status_code == 200:
        json_response = response.json()
        if json_response['results']:
            location = json_response['results'][0]['geometry']['location']
            return (location['lat'], location['lng'])
        
    return (None, None)


#Dataframe 위도 경도 추가
df2['위도'], df2['경도'] = zip(*df2['행정동'].map(geocode))
df2 = df2.dropna(subset = ['위도','경도']) # 유효하지 않은 위치 데이터는 제거 

#center lat, lng설정 
center_lat = df2['위도'].mean()
center_lng = df2['경도'].mean()

#Folium생성
map = folium.Map(location=[center_lat,center_lng], zoom_start = 12)


# heatmap으로 표현하여 시각적으로 보기 위해 표현. 
heat_data = [[row['위도'], row['경도'], row['MZ세대_유동인구']] for idx , row in df2.iterrows()]
heat_map = plugins.HeatMap(heat_data, radius=40, max_zoom=13, blur=15,max_val = 1.0)
map.add_child(heat_map)


# 잘 보이지 않으니 마커를 추가하자
for idx , row in df2.iterrows():
    if row['위도'] is not None and row['경도'] is not None:
        folium.Marker(
            location = (row['위도'], row['경도']),
            popup = f'{row["행정동"]} : 유동인구 {row["MZ세대_유동인구"]}',
            icon = folium.Icon(color = 'blue', icon = 'info-sign')
                    
        ).add_to(map)
    else :
        print(row['행정동'])


#지도저장 


map.save('heatmap2.html')

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

/var/folders/06/tbmdvc413xncjxzs56w_xd100000gn/T/ipykernel_1507/3830988957.py:33: UserWarning: The `max_val` parameter is no longer necessary. The largest intensity is calculated automatically.
  heat_map = plugins.HeatMap(heat_data, radius=40, max_zoom=13, blur=15,max_val = 1.0)