In [1]:
import pandas as pd

In [14]:
data1 = pd.read_csv('data/매장 관련/서울시 일반음식점 인허가 정보.csv', encoding='utf-8-sig')
data2 = pd.read_csv('data/매장 관련/서울시 휴게음식점 인허가 정보.csv', encoding='utf-8-sig')
data3 = pd.read_csv('data/매장 관련/서울시 제과점영업 인허가 정보.csv', encoding='utf-8-sig')

In [15]:
d1 = pd.concat([data1, data2], axis=0)
d2 = pd.concat([d1, data3], axis=0)

In [16]:
d2

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,...,소재지면적,소재지우편번호,지번주소,도로명주소,도로명우편번호,사업장명,최종수정일자,데이터갱신구분,데이터갱신일자,업태구분명
0,3030000,3030000-101-2023-00140,2023-03-31,NaN,1,영업/정상,1,영업,NaN,NaN,...,54.9,133-835,서울특별시 성동구 성수동2가 316-31,"서울특별시 성동구 연무장길 41-19, 지1층 B101호 (성수동2가)",4782.0,아가젤라또(성수),2023-03-31 11:17,I,02:00.0,기타
1,3030000,3030000-101-2023-00142,2023-03-31,NaN,1,영업/정상,1,영업,NaN,NaN,...,15,133-819,서울특별시 성동구 성수동1가 278-4,"서울특별시 성동구 성덕정9가길 14, 1층 (성수동1가)",4775.0,위트 에스프레소바,2023-03-31 16:09,I,02:00.0,기타
2,3030000,3030000-101-2023-00141,2023-03-31,NaN,1,영업/정상,1,영업,NaN,NaN,...,96.36,133-831,서울특별시 성동구 성수동2가 273-13 태광산업,"서울특별시 성동구 연무장15길 11, 태광산업 가(C)동 2층 C202호 (성수동2가)",4783.0,옥자 성수,2023-04-26 17:46,U,08:00.0,기타
3,3030000,3030000-101-2023-00210,2023-05-12,NaN,1,영업/정상,1,영업,NaN,NaN,...,162.19,133-827,서울특별시 성동구 성수동2가 310-53,"서울특별시 성동구 연무장길 28-12, 2층 (성수동2가)",4781.0,서울브루어리 성수 탭룸,2023-05-12 10:58,I,04:00.0,기타
4,3030000,3030000-101-2021-00044,2021-01-27,NaN,1,영업/정상,1,영업,NaN,NaN,...,82,133-827,서울특별시 성동구 성수동2가 325-2 서울숲한라시그마벨리,"서울특별시 성동구 성수이로 51, 1층 103A,103B호 (성수동2가)",4781.0,남영동 양문 성수역점,2023-03-31 15:39,U,02:00.0,기타
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,3030000,3030000-121-2022-00016,20220829,NaN,1,영업/정상,1,영업,NaN,NaN,...,45.54,133822,서울특별시 성동구 성수동1가 7-20,"서울특별시 성동구 왕십리로14길 19-2, 1층 (성수동1가)",4788.0,두투리에,2022-08-29 10:38,I,01:00.0,제과점영업
123,3030000,3030000-121-2022-00017,20220830,NaN,1,영업/정상,1,영업,NaN,NaN,...,26.4,133827,서울특별시 성동구 성수동2가 310-5,"서울특별시 성동구 연무장길 26, 1층 (성수동2가)",4781.0,카페 텅,2022-09-30 17:12,U,02:00.0,제과점영업
124,3030000,3030000-121-1997-00002,19970822,NaN,1,영업/정상,1,영업,NaN,NaN,...,76.64,133821,서울특별시 성동구 성수동1가 660-14,서울특별시 성동구 왕십리로 92 (성수동1가),4778.0,파리바게뜨 서울숲역점,2022-10-25 11:45,U,07:00.0,제과점영업
125,3030000,3030000-121-2022-00009,20220503,NaN,1,영업/정상,1,영업,NaN,NaN,...,31.1,133820,서울특별시 성동구 성수동1가 142-3,"서울특별시 성동구 성덕정길 32, 1층 (성수동1가)",4774.0,오복떡집,2022-05-03 17:01,I,07:00.0,제과점영업
126,3030000,3030000-121-2022-00019,2022-09-22,NaN,3,폐업,2,폐업,2023-11-15,NaN,...,150.0,133-834,서울특별시 성동구 성수동2가 300-11 에프투텔레콤,"서울특별시 성동구 아차산로 83, 에프투텔레콤 1층 (성수동2가)",4793.0,플럼프,2023-11-15 10:30,U,07:00.0,제과점영업

In [21]:
d2022 = d2[d2['인허가일자'].between('2022-01-01', '2022-12-31')]
d2022.sort_values('인허가일자', ascending=True, inplace=True)
d2022.reset_index()

C:\Users\Puser\AppData\Local\Temp\ipykernel_12476\2524048050.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d2022.sort_values('인허가일자', ascending=True, inplace=True)

,index,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,...,소재지면적,소재지우편번호,지번주소,도로명주소,도로명우편번호,사업장명,최종수정일자,데이터갱신구분,데이터갱신일자,업태구분명
0,392,3030000,3030000-101-2022-00002,2022-01-03,NaN,3,폐업,2,폐업,2023-02-02,...,57,133-826,서울특별시 성동구 성수동2가 269-63 성수에이원 지식산업센터,"서울특별시 성동구 뚝섬로17가길 48, 성수에이원 지식산업센터 1층 102호 (성수...",4785.0,해피치즈스마일 성수점,2023-02-02 9:07,U,04:00.0,기타
1,1430,3030000,3030000-101-2022-00012,2022-01-13,NaN,3,폐업,2,폐업,2023-06-16,...,63.62,133-825,서울특별시 성동구 성수동1가 685-337,"서울특별시 성동구 서울숲2길 11-12, 1층 (성수동1가)",4768.0,스웨이 성수,2023-06-16 13:45,U,08:00.0,기타
2,1429,3030000,3030000-101-2022-00020,2022-01-18,NaN,1,영업/정상,1,영업,NaN,...,38,133-827,서울특별시 성동구 성수동2가 310-21,"서울특별시 성동구 성수일로4길 45, 1층 (성수동2가)",4781.0,성수 매운갈비찜,2023-11-10 15:16,U,02:00.0,한식
3,1351,3030000,3030000-101-2022-00038,2022-02-11,NaN,3,폐업,2,폐업,2023-12-29,...,153.54,133-824,서울특별시 성동구 성수동1가 668-112,"서울특별시 성동구 서울숲2길 36, 2층 (성수동1가)",4768.0,야드 바이 비씨,2023-12-29 11:05,U,01:00.0,기타
4,413,3030000,3030000-104-2022-00010,2022-02-14,NaN,3,폐업,2,폐업,2023-10-27,...,181.37,133-827,서울특별시 성동구 성수동2가 321-70 태진섬유,"서울특별시 성동구 성수이로7가길 13, 1층 (성수동2가)",4781.0,잇덴굿 성수점,2023-10-27 11:28,U,09:00.0,커피숍
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,160,3030000,3030000-101-2022-00471,2022-12-15,NaN,1,영업/정상,1,영업,NaN,...,123.5,133-825,서울특별시 성동구 성수동1가 685-700 아크로 서울포레스트,"서울특별시 성동구 왕십리로 83-21, 디타워 스트리트동 지1층 B110호, B11...",4769.0,ttitto 띠또분식,2023-03-30 14:24,U,01:00.0,분식
88,4688,3030000,3030000-101-2022-00481,2022-12-20,NaN,3,폐업,2,폐업,2023-07-26,...,90.2,133-835,서울특별시 성동구 성수동2가 316-48,"서울특별시 성동구 연무장길 37-22, 1층, 2층 (성수동2가)",4782.0,더바투(THE BATU),2023-07-26 15:57,U,08:00.0,기타
89,134,3030000,3030000-104-2022-00167,2022-12-23,NaN,1,영업/정상,1,영업,NaN,...,55.55,133-822,서울특별시 성동구 성수동1가 7-15,"서울특별시 성동구 왕십리로14길 25, 1층 (성수동1가)",4788.0,쿠키도우즈(COOKIE DOUGHS),2023-04-19 12:49,U,01:00.0,일반조리판매
90,4709,3030000,3030000-101-2022-00486,2022-12-26,NaN,3,폐업,2,폐업,2023-11-17,...,41.1,133-822,서울특별시 성동구 성수동1가 13-209,"서울특별시 성동구 상원12길 34, 1층 105호 (성수동1가)",4790.0,시드니 김치찜(뚝섬점),2023-11-17 11:50,U,09:00.0,한식
91,4742,3030000,3030000-101-2022-00497,2022-12-30,NaN,1,영업/정상,1,영업,NaN,...,13,133-826,서울특별시 성동구 성수동2가 269-163,"서울특별시 성동구 연무장길 100-15, 1층 (성수동2가)",4785.0,성수닭꼬치,2023-09-11 15:53,U,03:00.0,한식

In [22]:
d2023 = d2[d2['인허가일자'].between('2023-01-01', '2023-12-31')]
d2023.sort_values('인허가일자', ascending=True, inplace=True)
d2023.reset_index()

C:\Users\Puser\AppData\Local\Temp\ipykernel_12476\3405603329.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d2023.sort_values('인허가일자', ascending=True, inplace=True)

,index,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,...,소재지면적,소재지우편번호,지번주소,도로명주소,도로명우편번호,사업장명,최종수정일자,데이터갱신구분,데이터갱신일자,업태구분명
0,27,3030000,3030000-101-2023-00009,2023-01-03,NaN,1,영업/정상,1,영업,NaN,...,87.65,133-824,서울특별시 성동구 성수동1가 668-24,"서울특별시 성동구 서울숲4길 23, 1층 (성수동1가)",4768.0,사길이삼,2023-03-06 11:40,U,08:00.0,한식
1,180,3030000,3030000-101-2023-00020,2023-01-10,NaN,1,영업/정상,1,영업,NaN,...,63.44,133-923,서울특별시 성동구 성수동1가 705 성수동우방아파트,"서울특별시 성동구 상원길 77, 성수동우방아파트 생활편익시설동 1층 101호 (성수...",4788.0,주식회사 리프레쉬먼트,2023-04-27 17:31,U,09:00.0,기타
2,4972,3030000,3030000-101-2023-00023,2023-01-12,NaN,1,영업/정상,1,영업,NaN,...,194.48,133-825,서울특별시 성동구 성수동1가 685-507,"서울특별시 성동구 서울숲2길 12-7, 1층, 3층 (성수동1가)",4768.0,플래드 카페,2023-06-23 18:30,U,05:00.0,기타
3,4973,3030000,3030000-101-2023-00022,2023-01-12,NaN,3,폐업,2,폐업,2023-08-23,...,31.25,133-833,서울특별시 성동구 성수동2가 299-104,"서울특별시 성동구 광나루로4길 8-1, 1층 (성수동2가)",4792.0,아는커피,2023-08-23 15:51,U,05:00.0,기타
4,5005,3030000,3030000-101-2023-00027,2023-01-19,NaN,1,영업/정상,1,영업,NaN,...,341.25,133-832,서울특별시 성동구 성수동2가 277-46,"서울특별시 성동구 성수이로24길 36, 2층 (성수동2가)",4798.0,오우드 성수2호점,2023-12-01 14:33,U,03:00.0,기타
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,372,3030000,3030000-101-2023-00551,2023-12-21,NaN,1,영업/정상,1,영업,NaN,...,100.81,133-831,서울특별시 성동구 성수동2가 273-52 더리브 세종타워,"서울특별시 성동구 아차산로 126, 더리브 세종타워 지1층 B108호 (성수동2가)",4783.0,게방식당,2023-12-21 11:20,I,03:00.0,한식
401,376,3030000,3030000-101-2023-00554,2023-12-22,NaN,1,영업/정상,1,영업,NaN,...,33.49,133-924,서울특별시 성동구 성수동1가 656-1016,"서울특별시 성동구 왕십리로8길 21, 지1층 (성수동1가)",4778.0,바타스 BATAS,2023-12-22 12:19,I,04:00.0,기타
402,363,3030000,3030000-101-2023-00556,2023-12-26,NaN,1,영업/정상,1,영업,NaN,...,200,133-834,서울특별시 성동구 성수동2가 289-224,"서울특별시 성동구 성수일로8길 39-1, 지하1층 (성수동2가)",4794.0,대저택,2023-12-26 16:56,I,08:00.0,기타
403,386,3030000,3030000-101-2023-00562,2023-12-29,NaN,1,영업/정상,1,영업,NaN,...,69.41,133-835,서울특별시 성동구 성수동2가 314-6 신성빌딩,"서울특별시 성동구 아차산로 96, 신성빌딩 1층 (성수동2가)",4782.0,한신우동 성수점,2024-01-11 12:40,U,03:00.0,한식
404,378,3030000,3030000-101-2023-00561,2023-12-29,NaN,1,영업/정상,1,영업,NaN,...,50.74,133-834,서울특별시 성동구 성수동2가 289-39,"서울특별시 성동구 아차산로7길 36, 1층 4호 (성수동2가)",4795.0,더양평해장국 성수역점,2023-12-29 14:20,I,01:00.0,한식

In [23]:
d2022.to_csv("성수동_신규매장_2022년.csv", index=False, encoding='utf-8-sig')
d2023.to_csv("성수동_신규매장_2023년.csv", index=False, encoding='utf-8-sig')