In [2]:
import pandas as pd

### 모든 지역 데이터 불러오기

In [3]:
data1 = pd.read_csv('data/트위터/twitter_강남구.csv', encoding='utf-8-sig')
data2 = pd.read_csv('data/트위터/twitter_강동구.csv', encoding='utf-8-sig')
data3 = pd.read_csv('data/트위터/twitter_강북구.csv', encoding='utf-8-sig')
data4 = pd.read_csv('data/트위터/twitter_강서구.csv', encoding='utf-8-sig')
data5 = pd.read_csv('data/트위터/twitter_관악구.csv', encoding='utf-8-sig')
data6 = pd.read_csv('data/트위터/twitter_광진구.csv', encoding='utf-8-sig')
data7 = pd.read_csv('data/트위터/twitter_구로구.csv', encoding='utf-8-sig')
data8 = pd.read_csv('data/트위터/twitter_동대문구.csv', encoding='utf-8-sig')
data9 = pd.read_csv('data/트위터/twitter_동작구.csv', encoding='utf-8-sig')
data10 = pd.read_csv('data/트위터/twitter_마포구.csv', encoding='utf-8-sig')
data11 = pd.read_csv('data/트위터/twitter_서대문구.csv', encoding='utf-8-sig')
data12 = pd.read_csv('data/트위터/twitter_서초구.csv', encoding='utf-8-sig')
data13 = pd.read_csv('data/트위터/twitter_성동구.csv', encoding='utf-8-sig')
data14 = pd.read_csv('data/트위터/twitter_성북구.csv', encoding='utf-8-sig')
data15 = pd.read_csv('data/트위터/twitter_송파구.csv', encoding='utf-8-sig')
data16 = pd.read_csv('data/트위터/twitter_양천구.csv', encoding='utf-8-sig')
data17 = pd.read_csv('data/트위터/twitter_영등포구.csv', encoding='utf-8-sig')
data18 = pd.read_csv('data/트위터/twitter_용산구.csv', encoding='utf-8-sig')
data19 = pd.read_csv('data/트위터/twitter_은평구.csv', encoding='utf-8-sig')
data20 = pd.read_csv('data/트위터/twitter_중구.csv', encoding='utf-8-sig')
data21 = pd.read_csv('data/트위터/twitter_중랑구.csv', encoding='utf-8-sig')

### 데이터프레임 합치기

In [4]:
d1 = pd.concat([data1, data2], axis=0)
d2 = pd.concat([d1, data3], axis=0)
d3 = pd.concat([d2, data4], axis=0)
d4 = pd.concat([d3, data5], axis=0)
d5 = pd.concat([d4, data6], axis=0)
d6 = pd.concat([d5, data7], axis=0)
d7 = pd.concat([d6, data8], axis=0)
d8 = pd.concat([d7, data9], axis=0)
d9 = pd.concat([d8, data10], axis=0)
d10 = pd.concat([d9, data11], axis=0)
d11 = pd.concat([d10, data12], axis=0)
d12 = pd.concat([d11, data13], axis=0)
d13 = pd.concat([d12, data14], axis=0)
d14 = pd.concat([d13, data15], axis=0)
d15 = pd.concat([d14, data16], axis=0)
d16 = pd.concat([d15, data17], axis=0)
d17 = pd.concat([d16, data18], axis=0)
d18 = pd.concat([d17, data19], axis=0)
d19 = pd.concat([d18, data20], axis=0)
d20 = pd.concat([d19, data21], axis=0)

In [5]:
d20

                                                tweet
0   신사 골뱅이신사\n\n골뱅이 존맛 배터지게 먹고왔어용\n#정한아_마니머거여ㅎㅎ\n#...
1   더보이즈 투어 폼 미춋다..\n예절샷 못 찍는 사람들의 만남\n 벽돌해피푸드 압구정...
2   코엑스 스시한판\n\n직원이 졸라 불친절해서 개빡쳤지만\n초밥 개맛있어서 화가 녹아...
3   민현이가 좋아하는 압구정 로데오 포케 맛집\n보울룸 <Bowl Room>\n이라고합...
4   진짜 맛있게 배터지게 먹고 엄청 웃어서 소화 다 됐다.. 나나투어 직전에 벌떡 일어...
..                                                ...
22  상봉 돼봉삼겹살\n\n돼봉모둠한판 중 시켰더염\n고기 다 구워서 가져다주시구 껍데기...
23  밥 잘 사주는 예쁜 (스테이) 누나\n\n우리 둘 다 양 적어서 저거 먹고 볶음밥이...
24  상봉 커피스터프\n로투스케이크도 수플레케이크도 너무 맛있는 곳 다른 케이크 종류도 ...
25  망우동 홍이네떡볶이\n\n떡볶이메이트 김후추랑 비를 맞으며 찾아온 후추떡볶이 멍맛있...
26   상봉 제주동화\n\n여기 완전 동화 속 그잡채。。♡ \n브런치도 맛있구\n#New...

[28814 rows x 1 columns]

### 중복 트윗 제거

In [10]:
data = d20.drop_duplicates()

In [11]:
data

                                                tweet
0   신사 골뱅이신사\n\n골뱅이 존맛 배터지게 먹고왔어용\n#정한아_마니머거여ㅎㅎ\n#...
1   더보이즈 투어 폼 미춋다..\n예절샷 못 찍는 사람들의 만남\n 벽돌해피푸드 압구정...
2   코엑스 스시한판\n\n직원이 졸라 불친절해서 개빡쳤지만\n초밥 개맛있어서 화가 녹아...
3   민현이가 좋아하는 압구정 로데오 포케 맛집\n보울룸 <Bowl Room>\n이라고합...
4   진짜 맛있게 배터지게 먹고 엄청 웃어서 소화 다 됐다.. 나나투어 직전에 벌떡 일어...
..                                                ...
22  상봉 돼봉삼겹살\n\n돼봉모둠한판 중 시켰더염\n고기 다 구워서 가져다주시구 껍데기...
23  밥 잘 사주는 예쁜 (스테이) 누나\n\n우리 둘 다 양 적어서 저거 먹고 볶음밥이...
24  상봉 커피스터프\n로투스케이크도 수플레케이크도 너무 맛있는 곳 다른 케이크 종류도 ...
25  망우동 홍이네떡볶이\n\n떡볶이메이트 김후추랑 비를 맞으며 찾아온 후추떡볶이 멍맛있...
26   상봉 제주동화\n\n여기 완전 동화 속 그잡채。。♡ \n브런치도 맛있구\n#New...

[28102 rows x 1 columns]

### 데이터프레임 csv로 저장

In [12]:
data.to_csv("트위터_통합.csv", index=False, encoding='utf-8-sig')

In [17]:
a = pd.read_excel('data/트위터/트위터_통합_a.xlsx')
b = pd.read_csv('트위터_통합.csv', encoding='utf-8-sig')

In [32]:
a

,tweet,full_name,brand
0,신사 골뱅이신사\n\n골뱅이 존맛 배터지게 먹고왔어용\n#정한아_마니머거여ㅎㅎ\n#...,골뱅이신사 신사,골뱅이신사
1,더보이즈 투어 폼 미춋다..\n예절샷 못 찍는 사람들의 만남\n 벽돌해피푸드 압구정...,벽돌해피푸드 압구정 / 디저트로이 압구정로데오 / 파스텔드나따 압구정 / 한스 압구...,벽돌해피푸드 / 디저트로이 / 파스텔드나따 / 한스 / 카츠바이콘반
2,코엑스 스시한판\n\n직원이 졸라 불친절해서 개빡쳤지만\n초밥 개맛있어서 화가 녹아...,스시한판 코엑스,스시한판
3,민현이가 좋아하는 압구정 로데오 포케 맛집\n보울룸 <Bowl Room>\n이라고합...,보울룸 압구정,보울룸
4,진짜 맛있게 배터지게 먹고 엄청 웃어서 소화 다 됐다.. 나나투어 직전에 벌떡 일어...,뱃고동 압구정,뱃고동
...,...,...,...
28783,사가정 카페이포크\n\n인스타 보고 찾아가서 별 기대 안했는데 \n생각했던 것보다 ...,카페이포크 사가정,카페이포크
28784,상봉 돼봉삼겹살\n\n돼봉모둠한판 중 시켰더염\n고기 다 구워서 가져다주시구 껍데기...,돼봉삼겹살 상봉,돼봉삼겹살
28785,상봉 커피스터프\n로투스케이크도 수플레케이크도 너무 맛있는 곳 다른 케이크 종류도 ...,커피스터프 상봉,커피스터프
28786,망우동 홍이네떡볶이\n\n떡볶이메이트 김후추랑 비를 맞으며 찾아온 후추떡볶이 멍맛있...,홍이네떡볶이 망우,홍이네떡볶이
28787,상봉 제주동화\n\n여기 완전 동화 속 그잡채。。♡ \n브런치도 맛있구\n#New...,제주동화 상봉,제주동화

In [33]:
b

                                                   tweet
0      신사 골뱅이신사\n\n골뱅이 존맛 배터지게 먹고왔어용\n#정한아_마니머거여ㅎㅎ\n#...
1      더보이즈 투어 폼 미춋다..\n예절샷 못 찍는 사람들의 만남\n 벽돌해피푸드 압구정...
2      코엑스 스시한판\n\n직원이 졸라 불친절해서 개빡쳤지만\n초밥 개맛있어서 화가 녹아...
3      민현이가 좋아하는 압구정 로데오 포케 맛집\n보울룸 <Bowl Room>\n이라고합...
4      진짜 맛있게 배터지게 먹고 엄청 웃어서 소화 다 됐다.. 나나투어 직전에 벌떡 일어...
...                                                  ...
28097  상봉 돼봉삼겹살\n\n돼봉모둠한판 중 시켰더염\n고기 다 구워서 가져다주시구 껍데기...
28098  밥 잘 사주는 예쁜 (스테이) 누나\n\n우리 둘 다 양 적어서 저거 먹고 볶음밥이...
28099  상봉 커피스터프\n로투스케이크도 수플레케이크도 너무 맛있는 곳 다른 케이크 종류도 ...
28100  망우동 홍이네떡볶이\n\n떡볶이메이트 김후추랑 비를 맞으며 찾아온 후추떡볶이 멍맛있...
28101   상봉 제주동화\n\n여기 완전 동화 속 그잡채。。♡ \n브런치도 맛있구\n#New...

[28102 rows x 1 columns]

In [49]:
c = pd.merge(a, b, on='tweet', how='right')
c

,tweet,full_name,brand
0,신사 골뱅이신사\n\n골뱅이 존맛 배터지게 먹고왔어용\n#정한아_마니머거여ㅎㅎ\n#...,골뱅이신사 신사,골뱅이신사
1,더보이즈 투어 폼 미춋다..\n예절샷 못 찍는 사람들의 만남\n 벽돌해피푸드 압구정...,벽돌해피푸드 압구정 / 디저트로이 압구정로데오 / 파스텔드나따 압구정 / 한스 압구...,벽돌해피푸드 / 디저트로이 / 파스텔드나따 / 한스 / 카츠바이콘반
2,코엑스 스시한판\n\n직원이 졸라 불친절해서 개빡쳤지만\n초밥 개맛있어서 화가 녹아...,스시한판 코엑스,스시한판
3,민현이가 좋아하는 압구정 로데오 포케 맛집\n보울룸 <Bowl Room>\n이라고합...,보울룸 압구정,보울룸
4,진짜 맛있게 배터지게 먹고 엄청 웃어서 소화 다 됐다.. 나나투어 직전에 벌떡 일어...,뱃고동 압구정,뱃고동
...,...,...,...
28807,상봉 돼봉삼겹살\n\n돼봉모둠한판 중 시켰더염\n고기 다 구워서 가져다주시구 껍데기...,돼봉삼겹살 상봉,돼봉삼겹살
28808,밥 잘 사주는 예쁜 (스테이) 누나\n\n우리 둘 다 양 적어서 저거 먹고 볶음밥이...,NaN,NaN
28809,상봉 커피스터프\n로투스케이크도 수플레케이크도 너무 맛있는 곳 다른 케이크 종류도 ...,커피스터프 상봉,커피스터프
28810,망우동 홍이네떡볶이\n\n떡볶이메이트 김후추랑 비를 맞으며 찾아온 후추떡볶이 멍맛있...,홍이네떡볶이 망우,홍이네떡볶이
28811,상봉 제주동화\n\n여기 완전 동화 속 그잡채。。♡ \n브런치도 맛있구\n#New...,제주동화 상봉,제주동화