In [3]:
import pandas as pd

In [5]:
data = pd.read_excel('data/광고성과_0701.xlsx')

In [4]:
data

         매체 광고 세트   소재         날짜  지출 금액   결과  결과당 비용
0   팝업스토어가자    1차   1안  2024.5.23  18060   73     247
1   팝업스토어가자    1차   1안  2024.5.24  73810  322     229
2   팝업스토어가자    1차   1안  2024.5.25  77154  318     243
3   팝업스토어가자    1차   1안  2024.5.26  78259  306     256
4   팝업스토어가자    1차   1안  2024.5.27  12131   35     347
..      ...   ...  ...        ...    ...  ...     ...
62       팝콘    4차  15안  2024.6.26  12616   28     451
63       팝콘    4차  15안  2024.6.27  10585   28     378
64       팝콘    4차  15안  2024.6.28  23627   47     503
65       팝콘    4차  15안  2024.6.29  61529  163     377
66       팝콘    4차  15안  2024.6.30  57497  120     479

[67 rows x 7 columns]

In [16]:
# 날짜 형식을 datetime으로 변환
data['날짜'] = pd.to_datetime(data['날짜'], format='%Y.%m.%d')

# 광고 시작 날짜로부터 며칠째인지를 계산
data['광고 시작 후 일수'] = data.groupby(['매체', '광고 세트', '소재'])['날짜'].rank(method='first')

# 1일차 데이터를 건너뛰고 분석
filtered_data = data[data['광고 시작 후 일수'] > 1]

# 결과당 비용의 변화를 계산
filtered_data['결과당 비용 변화'] = filtered_data.groupby(['매체', '광고 세트', '소재'])['결과당 비용'].diff()

# 결과당 비용이 증가하는 시점을 찾기 위해 변화가 양수인 시점을 선택
increasing_cost_points_filtered = filtered_data[filtered_data['결과당 비용 변화'] > 0]

# 광고 시작 후 결과당 비용이 증가하는 첫 번째 시점을 계산
first_increase_points = increasing_cost_points_filtered.groupby(['매체', '광고 세트', '소재']).agg({'광고 시작 후 일수': 'min'}).reset_index()

# 평균 일수 계산
average_increasing_cost_day_filtered = first_increase_points['광고 시작 후 일수'].mean()

# 결과 데이터프레임 출력
first_increase_points, average_increasing_cost_day_filtered

C:\Users\Puser\AppData\Local\Temp\ipykernel_18184\3154698588.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['결과당 비용 변화'] = filtered_data.groupby(['매체', '광고 세트', '소재'])['결과당 비용'].diff()

(        매체 광고 세트   소재  광고 시작 후 일수
 0       팝업    1차   1안         3.0
 1  팝업스토어가자    1차   1안         3.0
 2  팝업스토어가자    4차  19안         3.0
 3  팝업스토어가자    4차  20안         3.0
 4  팝업스토어가자    4차  21안         3.0
 5       팝콘    1차   2안         3.0
 6       팝콘    2차   2안         4.0
 7       팝콘    4차  15안         3.0
 8       팝콘    4차  27안         4.0,
 3.2222222222222223)

In [17]:
first_increase_points

        매체 광고 세트   소재  광고 시작 후 일수
0       팝업    1차   1안         3.0
1  팝업스토어가자    1차   1안         3.0
2  팝업스토어가자    4차  19안         3.0
3  팝업스토어가자    4차  20안         3.0
4  팝업스토어가자    4차  21안         3.0
5       팝콘    1차   2안         3.0
6       팝콘    2차   2안         4.0
7       팝콘    4차  15안         3.0
8       팝콘    4차  27안         4.0

In [18]:
average_increasing_cost_day_filtered

3.2222222222222223